#!/usr/bin/env python3
"""
query_spaces_docs.py - Fast search and query tool for Spaces Starlark documentation.

Extracts, indexes, and queries documentation generated by 'spaces docs', with local caching
in ~/.cache/spaces_docs/ for sub-millisecond retrieval.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

CACHE_DIR = Path(os.environ.get("SPACES_DOCS_CACHE", Path.home() / ".cache" / "spaces_docs"))
RAW_DOCS_CACHE = CACHE_DIR / "spaces_docs_raw.md"
INDEX_CACHE = CACHE_DIR / "spaces_docs_index.json"


def get_spaces_bin() -> str:
    spaces_bin = os.environ.get("SPACES_BIN")
    if spaces_bin and os.path.isfile(spaces_bin) and os.access(spaces_bin, os.X_OK):
        return spaces_bin
    for candidate in [str(Path.home() / ".local/bin/spaces"), "/usr/local/bin/spaces"]:
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return "spaces"


def get_raw_docs(force_refresh: bool = False) -> str:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    spaces_bin = get_spaces_bin()

    needs_fetch = force_refresh or not RAW_DOCS_CACHE.is_file()
    if not needs_fetch and os.path.isfile(spaces_bin):
        try:
            bin_mtime = os.path.getmtime(spaces_bin)
            cache_mtime = RAW_DOCS_CACHE.stat().st_mtime
            if bin_mtime > cache_mtime:
                needs_fetch = True
        except Exception:
            pass

    if needs_fetch:
        try:
            raw = subprocess.check_output([spaces_bin, "docs"], stderr=subprocess.PIPE).decode("utf-8", errors="ignore")
            RAW_DOCS_CACHE.write_text(raw, encoding="utf-8")
            # Invalidate index cache
            if INDEX_CACHE.is_file():
                INDEX_CACHE.unlink()
            return raw
        except Exception as e:
            if RAW_DOCS_CACHE.is_file():
                sys.stderr.write(f"Warning: Failed to execute '{spaces_bin} docs' ({e}), using cached docs.\n")
                return RAW_DOCS_CACHE.read_text(encoding="utf-8", errors="ignore")
            sys.stderr.write(f"Error: Failed to execute '{spaces_bin} docs': {e}\n")
            sys.exit(1)
    else:
        return RAW_DOCS_CACHE.read_text(encoding="utf-8", errors="ignore")


def parse_docs(raw_text: str) -> dict:
    if INDEX_CACHE.is_file():
        try:
            return json.loads(INDEX_CACHE.read_text(encoding="utf-8"))
        except Exception:
            pass

    modules = {}
    current_module = "global"
    current_func = None
    func_lines = []

    lines = raw_text.splitlines()

    def save_func():
        nonlocal current_func, func_lines
        if current_func and current_module:
            if current_module not in modules:
                modules[current_module] = {"description": "", "functions": {}}
            doc_content = "\n".join(func_lines).strip()
            modules[current_module]["functions"][current_func] = doc_content
        current_func = None
        func_lines = []

    for line in lines:
        if line.startswith("## "):
            save_func()
            current_module = line[3:].strip()
            if current_module not in modules:
                modules[current_module] = {"description": "", "functions": {}}
        elif line.startswith("### "):
            save_func()
            func_name = line[4:].strip()
            if func_name.endswith("()"):
                func_name = func_name[:-2]
            current_func = func_name
            func_lines = [line]
        else:
            if current_func:
                func_lines.append(line)
            elif current_module in modules and not modules[current_module]["description"] and line.strip() and not line.startswith("---"):
                modules[current_module]["description"] = line.strip()

    save_func()

    try:
        INDEX_CACHE.write_text(json.dumps(modules, indent=2), encoding="utf-8")
    except Exception:
        pass

    return modules


def list_modules(modules: dict, as_json: bool = False):
    if as_json:
        result = [
            {"module": mod, "function_count": len(data["functions"]), "description": data.get("description", "")}
            for mod, data in sorted(modules.items())
        ]
        print(json.dumps(result, indent=2))
        return

    print(f"{'Module':<18} | {'Functions':<10} | {'Description'}")
    print("-" * 80)
    for mod, data in sorted(modules.items()):
        desc = data.get("description", "")
        if len(desc) > 50:
            desc = desc[:47] + "..."
        print(f"{mod:<18} | {len(data['functions']):<10} | {desc}")
    total_funcs = sum(len(d["functions"]) for d in modules.values())
    print("-" * 80)
    print(f"Total: {len(modules)} modules, {total_funcs} functions available in Starlark.")


def list_functions(modules: dict, target_module: str = None, as_json: bool = False):
    records = []
    for mod, data in sorted(modules.items()):
        if target_module and mod.lower() != target_module.lower():
            continue
        for fn in sorted(data["functions"].keys()):
            records.append({"module": mod, "function": fn})

    if as_json:
        print(json.dumps(records, indent=2))
        return

    for rec in records:
        print(f"{rec['module']}.{rec['function']}()")
    print(f"\nTotal: {len(records)} functions.")


def show_module(modules: dict, module_name: str, as_json: bool = False):
    matched = None
    for mod, data in modules.items():
        if mod.lower() == module_name.lower():
            matched = (mod, data)
            break

    if not matched:
        print(f"Error: Module '{module_name}' not found. Available modules: {', '.join(sorted(modules.keys()))}")
        sys.exit(1)

    mod, data = matched
    if as_json:
        print(json.dumps({mod: data}, indent=2))
        return

    print(f"================================================================================")
    print(f" Module: {mod} ({len(data['functions'])} functions)")
    print(f"================================================================================\n")
    for fn, doc in sorted(data["functions"].items()):
        print(doc)
        print("\n" + "-" * 40 + "\n")


def show_function(modules: dict, func_name: str, as_json: bool = False):
    clean_func = func_name
    if clean_func.endswith("()"):
        clean_func = clean_func[:-2]

    target_mod = None
    if "." in clean_func:
        target_mod, clean_func = clean_func.split(".", 1)

    matches = []
    for mod, data in modules.items():
        if target_mod and mod.lower() != target_mod.lower():
            continue
        for fn, doc in data["functions"].items():
            if fn.lower() == clean_func.lower():
                matches.append((mod, fn, doc))

    if not matches:
        print(f"Error: Function '{func_name}' not found.")
        sys.exit(1)

    if as_json:
        result = [{"module": m, "function": f, "doc": d} for m, f, d in matches]
        print(json.dumps(result, indent=2))
        return

    for mod, fn, doc in matches:
        print(f"=== {mod}.{fn}() ===")
        print(doc)
        print()


def search_docs(raw_text: str, modules: dict, query: str, limit: int = 5, as_json: bool = False):
    pattern = re.compile(re.escape(query), re.IGNORECASE)
    results = []

    for mod, data in modules.items():
        for fn, doc in data["functions"].items():
            if pattern.search(doc) or pattern.search(f"{mod}.{fn}"):
                lines = doc.splitlines()
                snippets = []
                for idx, line in enumerate(lines):
                    if pattern.search(line):
                        start = max(0, idx - 1)
                        end = min(len(lines), idx + 2)
                        ctx = "\n".join(f"  {lines[i]}" for i in range(start, end))
                        snippets.append(ctx)
                        if len(snippets) >= 2:
                            break
                results.append({
                    "module": mod,
                    "function": fn,
                    "snippets": snippets,
                    "doc": doc
                })
                if len(results) >= limit:
                    break
        if len(results) >= limit:
            break

    if as_json:
        print(json.dumps(results, indent=2))
        return

    if not results:
        print(f"No documentation matches found for '{query}'.")
        return

    print(f"Found {len(results)} matches for '{query}':\n")
    for r in results:
        print(f"=== {r['module']}.{r['function']}() ===")
        for snip in r["snippets"]:
            print(snip)
            print("  ---")
        print()


def main():
    parser = argparse.ArgumentParser(description="Query Spaces Starlark built-in and standard library documentation.")
    parser.add_argument("query", nargs="?", help="Search keyword or topic")
    parser.add_argument("--list", action="store_true", help="List all Starlark modules")
    parser.add_argument("--list-funcs", action="store_true", help="List all functions across modules")
    parser.add_argument("--module", "-m", help="Show all documentation for a specific module (e.g., workspace, fs, run)")
    parser.add_argument("--func", "-f", help="Show documentation for a specific function (e.g., load_value, add_exec)")
    parser.add_argument("--limit", type=int, default=5, help="Max search results to display (default: 5)")
    parser.add_argument("--refresh", action="store_true", help="Force refresh of documentation cache")
    parser.add_argument("--json", action="store_true", help="Output results in JSON format")
    args = parser.parse_args()

    raw_text = get_raw_docs(force_refresh=args.refresh)
    modules = parse_docs(raw_text)

    if args.list:
        list_modules(modules, as_json=args.json)
    elif args.list_funcs:
        list_functions(modules, target_module=args.module, as_json=args.json)
    elif args.module:
        show_module(modules, args.module, as_json=args.json)
    elif args.func:
        show_function(modules, args.func, as_json=args.json)
    elif args.query:
        search_docs(raw_text, modules, args.query, limit=args.limit, as_json=args.json)
    else:
        list_modules(modules, as_json=args.json)


if __name__ == "__main__":
    main()
